### ISSUE TITLE
module yaml needed

### ISSUE THREAD

**Issue by FreeBlues** [NeonMercury/python-lua#1]
Please desc any module needed in the README doc.

```
Air:python-lua admin$ python3.5 __main__.py t.py
Traceback (most recent call last):
  File "__main__.py", line 7, in <module>
    from pythonlua.config import Config
  File "/Users/admin/GitHub/python-lua/pythonlua/config.py", line 3, in <module>
    import yaml
ImportError: No module named 'yaml'
Air:python-lua admin$
```

**Comment by FreeBlues** [comment]
The similar: when runtests.py module colorama needed

```
Air:python-lua admin$ python3.5 runtests.py 
Traceback (most recent call last):
  File "runtests.py", line 10, in <module>
    from colorama import init, Fore, Style
ImportError: No module named 'colorama'
Air:python-lua admin$
```

**Comment by NeonMercury** [comment]
It's all in the requirements.txt. I think it's enough.
